#ifndef SETTING_NAMES_H
#define SETTING_NAMES_H

#define INI_FILENAME "GlovisdomNaughtyWord.ini"

#define ORG_NAME "glövisdom"
#define APP_NAME "NaughtyWord"
#define APP_INIT "NaughtyWord Init"
#define APP_INIT_NUMBER "24937859"
#define APP_LANGUAGE "Language"
#define APP_LANGUAGE_DEFAULT APP_LANGUAGE_TC
#define APP_LANGUAGE_TC "tc"    //Tradictional Chinese
#define APP_LANGUAGE_EN "en"
#define APP_LANGUAGE_SC "sc"    //Simplified Chinese

/* !!!Remove following settings to QML in the future !!! */

#define DECK_GROUPE "Deck"
#define DEFAULT_DECK_PATH "Default deck path"
#define DEFAULT_DECK_PATH_NAME "decks"

#define DICT_GROUPE "Dictionary"
#define DICT_DEFAULT "Default"
#define DICT_DEFAULT_NAME ""
#define DICT_DEFAULT_PATH "Folder"
#define DICT_DEFAULT_PATH_NAME "dictionaries"

#define ANKI_GROUPE "AnkiPackage"
#define ANKI_DEFAULT_PATH "PackagePath"
#define ANKI_DEFAULT_PATH_NAME "decks/anki"


//#define FAST_HAND_GROUP "FastHand"
//#define FAST_HAND_QUESTION "Question"
//#define FAST_HAND_QUESTION_DEFAULT "\xE5\xAD\x97\xE5\xBD\x99" //"字彙"
//#define FAST_HAND_ANSWER "Answer"
//#define FAST_HAND_ANSWER_DEFAULT "\xE5\x9C\x96\xE7\x89\x87" //"圖片"
//#define FAST_HAND_EASINESS "GaveOverEasiness"
//#define FAST_HAND_EASINESS_DEFAULT "Hard"
//#define FAST_HAND_CARDTYPE "CardType"
//#define FAST_HAND_CARDTYPE_DEFAULT "\xE6\x89\x80\xE6\x9C\x89\xE5\x96\xAE\xE5\xAD\x97" //"所有單字"
//#define FAST_HAND_DEALINGTYPE "DealingType"
//#define FAST_HAND_DEALINGTYPE_DEFAULT "\xE9\x9A\xA8\xE6\xA9\x9F"    //"隨機"
//#define INSANITY_GROUP "Insanity"
//#define INSANITY_QUESTION "Question"
//#define INSANITY_QUESTION_DEFAULT "\xE5\x9C\x96\xE7\x89\x87\xE8\xA8\x98\xE6\x86\xB6"  //"圖片記憶"
//#define INSANITY_EASINESS "Easiness"
//#define INSANITY_EASINESS_DEFAULT "Hard"
//#define INSANITY_CARDTYPE "CardType"
//#define INSANITY_CARDTYPE_DEFAULT "\xE6\x89\x80\xE6\x9C\x89\xE5\x96\xAE\xE5\xAD\x97" //"所有單字"
//#define INSANITY_DEALINGTYPE "DealingType"
//#define INSANITY_DEALINGTYPE_DEFAULT "\xE9\x9A\xA8\xE6\xA9\x9F"    //"隨機"
//#define INSANITY_TEACHER_LEVEL "teacher"
//#define INSANITY_TEACHER_LEVEL_DEFAULT "0"
//#define INSANITY_SMART_LEVEL "smart"
//#define INSANITY_SMART_LEVEL_DEFAULT "0"
//#define INSANITY_INVISIBLE_LEVEL "invisible"
//#define INSANITY_INVISIBLE_LEVEL_DEFAULT "0"
//#define INSANITY_GRAVITY_LEVEL "gravity"
//#define INSANITY_GRAVITY_LEVEL_DEFAULT "0"
//#define INSANITY_SHRINKER_LEVEL "shrinker"
//#define INSANITY_SHRINKER_LEVEL_DEFAULT "0"
//#define INSANITY_REDBULL_LEVEL "redBull"
//#define INSANITY_REDBULL_LEVEL_DEFAULT "0"
//#define AUDIO_SETTING_GROUP "Audio"
//#define AUDIO_SOUND_VOLUME "SoundVolume"
//#define AUDIO_SOUND_VOLUME_DEFAULT "1"
//#define AUDIO_MUSIC_VOLUME "MusicVolume"
//#define AUDIO_MUSIC_VOLUME_DEFAULT "0.5"
//#define USER_GROUP "User"
//#define USER_LAST_INPUT_NAME "LastInputName"
//#define USER_LAST_INPUT_NAME_DEFAULT "glovisdom"
//#define USER_COINS "Coins"
//#define USER_COINS_DEFAULT "0"
//#define USER_GEMS "Gems"
//#define USER_GEMS_DEFAULT "0"

//#define CLOUD_DRIVE_GROUP "CloudDrive"
//#define CLOUD_GG_TOKEN "GgToken"
//#define CLOUD_GG_TOKEN_EXPIRED_TIME "GgTokenExpiredTime"
//#define CLOUD_GG_REFRESH_TOKEN "GgRefreshToken"
//#define CLOUD_ALL_DEFAULT ""

//#define ENGINEERINGSETTING_GROUP "Engineering"
//#define ENGINEERING_INSANITY_BACKGROUND "insanityBackground"
//#define ENGINEERING_INSANITY_BACKGROUND_DEFAULT "0"
//#define ENGINEERING_PLAY_SPEECH_WHEN_CORRECT "playSpeechWhenCorrect"
//#define ENGINEERING_PLAY_SPEECH_WHEN_CORRECT_DEFAULT "Yes"

//#define ENGINEERING_PAGE1_LAYOUT "page1Layout"
//#define ENGINEERING_PAGE1_LAYOUT_DEFAULT "Golden"
//#define ENGINEERING_DECK_LAYOUT "deckLayout"
//#define ENGINEERING_DECK_LAYOUT_DEFAULT "2"
//#define ENGINEERING_GAME_LAYOUT "gameLayout"
//#define ENGINEERING_GAME_LAYOUT_DEFAULT "2"

//#define TUTORIAL_GROUP "Tutorial"
//#define TUTORIAL_VERY_BEGINNING "Beginning"
//#define TUTORIAL_SELECT_DECK "SelectDeck"
//#define TUTORIAL_SELECT_ANKI "SelectAnkiPractice"
//#define TUTORIAL_SELECT_ANY_GAME "SelectAnyGame"
//#define TUTORIAL_HOW_TO_USE_ANKI1 "HowToUseAnki1"
//#define TUTORIAL_HOW_TO_USE_ANKI2 "HowToUseAnki2"
//#define TUTORIAL_HOW_TO_USE_ANKI3 "HowToUseAnki3"
//#define TUTORIAL_HOW_TO_USE_ANKI4 "HowToUseAnki4"
//#define TUTORIAL_USE_DICTIONARY "UseDictionary"
//#define TUTORIAL_SELECT_IMAGE "SelectImage"
//#define TUTORIAL_USE_ANOTHER_KEY_WORD "UseAnotherKeyWord"
//#define TUTORIAL_SAVE_CARD "SaveCard"
//#define TUTORIAL_INSANITY_INTRO "InsanityIntro"
//#define TUTORIAL_MOVE_EINSTEIN "MoveEinstein"
//#define TUTORIAL_ANSWER_QUESTION1 "AnswerTheQuestion1"
//#define TUTORIAL_POWER_UP_INTRO "PowerUpIntro"
//#define TUTORIAL_FLIP_MATCH_INTRO "FlipMatchIntro"
//#define TUTORIAL_ALL_DEFAULT "0"

#endif // SETTING_NAMES_H


